#server:
#   port: 8081
#socket:
#    host: localhost
#    port: 9091
#
#spring:
#  application:
#    name: websocket-client-service
#
#client-username: user1
#client-password: password1
#
#reconnect:
#  delay:
#    ms: 5000
#
#heartbeat:
#  interval:
#    ms: 10000   # every 10 seconds

server:
  port: 8081   # REST/Swagger UI port for client

spring:
  application:
    name: websocket-client-service

socket:
  host: localhost
  port: 9091   # Connects to server socket

client-username: user1
client-password: password1

reconnect:
  delay:
    ms: 5000   # 5s reconnect delay

heartbeat:
  interval:
    ms: 10000  # 10s heartbeat interval (must be < server timeout)